<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="wangsy-PC" name="login test" tests="3" failures="2" timestamp="24 Aug 2016 09:44:33 GMT" time="20.712" errors="0">
  <testcase name="testLogin" time="2.974" classname="com.wangsy.doTest.LoginTest"/>
  <testcase name="testLogin" time="0.969" classname="com.wangsy.doTest.LoginTest">
    <failure type="java.lang.AssertionError" message="expected [] but found [登录]">
      <![CDATA[java.lang.AssertionError: expected [] but found [登录]
	at com.wangsy.doTest.LoginTest.testLogin(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- testLogin -->
  <testcase name="testLogin" time="1.46" classname="com.wangsy.doTest.LoginTest">
    <failure type="java.lang.AssertionError" message="expected [] but found [登录]">
      <![CDATA[java.lang.AssertionError: expected [] but found [登录]
	at com.wangsy.doTest.LoginTest.testLogin(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- testLogin -->
</testsuite> <!-- login test -->
